routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/awal', function () {
    return view('welcome');
});
Route::get('/pegawai/cetak_pdf','PostController@generatePDF');
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoryController');
    Route::resource('tags', 'TagController');
    Route::resource('posts', 'PostController');
    Route::get('/trashed_posts', 'PostController@trashed')->name('posts.trashed');
    Route::get('/restore/{id}', 'PostController@restore')->name('posts.restore');
    Route::get('/users/{user}/profile', 'UserController@edit')->name('user.edit');
    Route::post('/users/{user}/profile', 'UserController@update')->name('user.update');
    Route::get('/users/{user}/show', 'UserController@tampil')->name('user.tampil');;
});
Route::group(['middleware' => ['auth', 'VerifyAdmin']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/users/index', 'UserController@index')->name('users.index');
    Route::post('/users/{user}/admin_role', 'UserController@make_admin')->name('users.admin_role');
    Route::post('/users/{user}/writer_role', 'UserController@make_writer')->name('users.writer_role');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];
    public function posts()
    {
        return $this->belongsToMany('App\Post');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TagValidation;
use Illuminate\Http\Request;
use App\Tag;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tags.index')->with('tags', Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagValidation $request)
    {
        Tag::create($request->all());
        session()->flash('success', 'Tag added succesfully');
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagValidation $request, Tag $tag)
    {
        $tag->name = $request->name;
        $tag->save();
        session()->flash('success', 'tag updated succesfully');
        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        session()->flash('destroy', 'tag deleted');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        {{isset($tag) ? "Update tag": "Add a new tag"}}
        @if (session()->has('error'))
            <div class="alert alert-danger mt-1 mb-0 fade show flash" role="alert">
                {{session()->get('error')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

        @endif
    </div>
    <div class="card-body">
        <form action="{{isset($tag)?route('tags.update',$tag->id): route('tags.store')}}" method="POST">

            <div class="form-group">
                @csrf
                @if (isset($tag))
                @method('PUT')
                @endif

                <label for="name">tag Name</label>
            <input id="name" value="{{isset($tag)?$tag->name:old('name')}}" class="@error('name') is-invalid @enderror form-control" type="text" name="name">

            </div>
            @error('name')
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{$message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            @enderror
            <div class="form-group">
                <button type="submit" class="btn btn-success">{{isset($tag)?"Update":"Save"}}</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
   @if (session()->has('success'))
   <div class="alert alert-success mt-1 mb-0 fade show flash" role="alert">
      {{session()->get('success')}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
   </div>
   @endif
   @if (session()->has('destroy'))
   <div class="alert alert-danger mt-1 mb-0 fade show flash" role="alert">
      {{session()->get('destroy')}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
   </div>
   @endif
   <div class="card-header">
      <div class="clearfix">
         <span>All Tags</span>
         <a href="{{route('tags.create')}}" class="btn btn-info float-right">Add tag</a>
      </div>
   </div>
   <div class="card-body p-0">
      {{-- table --}}
      <table  class="table table-striped">
         <tbody>
            @forelse ($tags as $tag)
            <tr>
               <td>
                   <span>{{$tag->name}}</span>
                   <span class="badge badge-info">{{$tag->posts->count()}}</span>
                </td>

               <td>
                  <form action="{{route('tags.destroy',$tag->id)}}" method="POST" class="float-right ml-2">
                     @csrf
                     @method('DELETE')
                     <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                  </form>
                  <a href="{{route('tags.edit',$tag->id)}}" class="btn btn-success float-right btn-sm">Edit</a>
               </td>
            </tr>
            @empty
            <p class="card-text text-center mt-3">No tags yet</p>
            @endforelse
         </tbody>
      </table>
      {{-- end table --}}
   </div>
</div>
@endsection