routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/awal', function () {
    return view('welcome');
});
Route::get('/pegawai/cetak_pdf','PostController@generatePDF');
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoryController');
    Route::resource('tags', 'TagController');
    Route::resource('posts', 'PostController');
    Route::get('/trashed_posts', 'PostController@trashed')->name('posts.trashed');
    Route::get('/restore/{id}', 'PostController@restore')->name('posts.restore');
    Route::get('/users/{user}/profile', 'UserController@edit')->name('user.edit');
    Route::post('/users/{user}/profile', 'UserController@update')->name('user.update');
    Route::get('/users/{user}/show', 'UserController@tampil')->name('user.tampil');;
});
Route::group(['middleware' => ['auth', 'VerifyAdmin']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/users/index', 'UserController@index')->name('users.index');
    Route::post('/users/{user}/admin_role', 'UserController@make_admin')->name('users.admin_role');
    Route::post('/users/{user}/writer_role', 'UserController@make_writer')->name('users.writer_role');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    protected $fillable = ['title', 'description', 'content', 'image', 'category_id', 'user_id'];
    public function category()
    {
        return $this->belongsTo('App\Category');
    }
    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function hastags($tagId)
    {
        return in_array($tagId, $this->tags->pluck('id')->toArray());
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostValidation;
use App\Http\Requests\UpadtePostValidation;
use Illuminate\Http\Request;
use App\Post;
use App\Tag;
use App\Category;
use Illuminate\Support\Facades\Storage;
use Yajra\Datatables\Datatables;
use PDF;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts_pagination = Post::paginate(5);
        return view('posts.index')->with('posts', $posts_pagination);
    }
    
      public function generatePDF()
    {
        $pegawai = Post::all();
 
    	$pdf = PDF::loadview('posts.index')->with('posts', $posts_pagination);
    	return $pdf->download('laporan-pegawai-pdf');
    }
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {

        $this->middleware('checkCategories')->only('create');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostValidation $request)
    {

        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
  
        $imageName = time().'.'.$request->image->extension();  
   
        $request->image->move(public_path('img'), $imageName);
   
        $post = Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $request->content,
            'image' => $imageName ,
            'category_id' => $request->category_id,
            'user_id' => $request->user_id
        ]);
        if ($request->tags_id) {
            $post->tags()->attach($request->tags_id);
        }
        session()->flash('success', 'Post added successfuly');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $user = $post->user;
        $latestpost = Post::orderBy('created_at', 'desc')->take(5)->get();
        return view('pages.single', ['post' => $post, 'categories' => Category::all(), 'tags' => Tag::all(), 'user' => $user, 'latest' => $latestpost]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('posts.create', ['post' => $post, 'categories' => Category::all(), 'tags' => Tag::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpadtePostValidation $request, Post $post)
    {
        $data = $request->only(['title', 'description', 'content', 'category_id']);
        if ($request->hasfile('image')) {
            $image = $request->image->store('images', 'public');
            Storage::disk('public')->delete($post->image);
            $data['image'] = $image;
        };
        if ($request->tags_id) {
            $post->tags()->sync($request->tags_id);
        }
        session()->flash('success', 'Post updated successfuly');
        $post->update($data);
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->where('id', $id)->first();
        if ($post->trashed()) {
            Storage::disk('public')->delete($post->image);
            $post->forceDelete();
            session()->flash('destroy', 'post deleted succesfuly');
            return redirect(route('posts.trashed'));
        } else {
            $post->delete();
            session()->flash('destroy', 'post trashed succesfuly');
            return redirect(route('posts.index'));
        }
    }
    public function trashed()
    {
        $trashed = Post::onlyTrashed()->get();
        return view('posts.trashed')->withPosts($trashed);
    }
    public function restore($id)
    {
        $post = Post::withTrashed()->find($id)->restore();
        session()->flash('success', 'Post restored successfuly');
        return redirect(route('posts.trashed'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    <div class="card-header">
        <span>
            {{isset($post) ? "Update Post": "Add a new Post"}}
        </span>
        @if ($errors->any())
            <div >
                @foreach ($errors->all() as $error)
                    <div class="alert alert-danger alert-dismissible fade show mb-1" role="alert">
                        {{ $error }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                @endforeach
            </div>
        @endif


    </div>
    <div class="card-body">
        <form action="{{isset($post)?route('posts.update',$post->id): route('posts.store')}}" method="POST" enctype="multipart/form-data">

            @csrf
            @if (isset($post))
            @method('PUT')
            @endif
            <div class="form-group">
                <label for="title">Title</label>
                <input id="title" placeholder="Post Title" value="{{isset($post)?$post->title:old('title')}}" class="form-control" type="text" name="title">
            </div>


                <input   value="{{Auth::user()->id}}" type="hidden" name="user_id">

            <div class="form-group">
                <label for="description">description</label>
                <textarea id="description"  placeholder="Post description" class="form-control" rows="2" name="description">{{isset($post)?$post->description:old('description')}}</textarea>
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <textarea id="content"  placeholder="Post content" class="form-control" rows="4" name="content">{{isset($post)?$post->content:old('content')}}</textarea>
            </div>
            @if (!isset($post))

            <div class="form-group">
                <label for="image">Image</label>
                <input id="image"  class="form-control-file" type="file" name="image">
            </div>
            @else

               <div>
                   <img src="{{asset('img/'.$post->image)}}" alt="image" style="width:100px;height:100px">
                </div>
                <div class="form-group">
                    <label for="image">Change Image</label>
                    <input id="image"  class="form-control-file" type="file" name="image">
                </div>
            @endif
            <div class="form-group">
                <label for="category_id">Select Category</label>
                <select class="form-control" id="category_id" name="category_id">
                  @foreach ($categories as $category)
                      <option value="{{$category->id}}">{{$category->name}}</option>
                  @endforeach
                </select>
              </div>
              @if ($tags->count()>=1)

              <div class="form-group">
                  <label for="tags_id">Select Tags</label>
                  <select class="form-control" id="tags_id" name="tags_id[]" multiple>
                    @foreach ($tags as $tag)
                        <option value="{{$tag->id}}"
                            @if (isset($post) && $post->hastags($tag->id))
                             selected
                            @endif>{{$tag->name}}</option>
                    @endforeach
                  </select>
                </div>
              @endif
            <div class="form-group">
                <button type="submit" class="btn btn-success">{{isset($post)?"Update":"Save"}}</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        <div class="clearfix">

            <span>All Posts</span>
            <a href="{{route('posts.create')}}" class="btn btn-info float-right">Add Post</a>
        </div>
        @if (session()->has('success'))
        <div class="alert alert-success mt-1 mb-0 fade show flash" role="alert">
            {{session()->get('success')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

        @endif
        @if (session()->has('destroy'))
        <div class="alert alert-danger mt-1 mb-0 fade show flash" role="alert">
            {{session()->get('destroy')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

        @endif
    </div>
    <div class="card-body p-0">
        {{-- table --}}
        @if ($posts->count()<=0)
        <p class="card-text m-3 text-center">No Post yet</p>

        @else

        <table  class="table table-striped table-bordered">
            <thead>
                <th>Image</th>
                <th>Title</th>
                <th>Actions</th>

            </thead>
            <tbody>

                @foreach ($posts as $post)
                <tr>
                    <td>
                        <img src="{{asset('img/'.$post->image)}}" alt="image" style="width:120px;background-size:cover">
                    </td>
                    <td style="vertical-align:middle;" >{{$post->title}}</td>
                    <td style="vertical-align:middle;">
                        <form action="{{route('posts.destroy',$post->id)}}" method="POST" class="float-right ml-2">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">Trash</button>
                        </form>
                        <a href="{{route('posts.edit',$post->id)}}" class="btn btn-success float-right btn-sm">Edit</a>
                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
        {{-- end table --}}
        @endif
        <nav class="d-flex justify-content-center">

            {{$posts->links()}}
        </nav>
    </div>
</div>

@endsection

resources/views/posts/trashed.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        <div class="clearfix">

            <span>Trashed Posts</span>
        </div>
        @if (session()->has('success'))
        <div class="alert alert-success mt-1 mb-0 fade show flash" role="alert">
            {{session()->get('success')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

        @endif
        @if (session()->has('destroy'))
        <div class="alert alert-danger mt-1 mb-0 fade show flash" role="alert">
            {{session()->get('destroy')}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

        @endif
    </div>
    <div class="card-body p-0">
        @if ($posts->count()<=0)
        <p class="card-text m-3 text-center">No trashed Post</p>

        @else
        {{-- table --}}
        <table  class="table table-striped table-bordered">
            <thead>
                <th>Image</th>
                <th>Title</th>
                <th>Actions</th>

            </thead>
            <tbody>

                @foreach ($posts as $post)
                <tr>
                    <td>
                        <img src="{{asset('storage/'.$post->image)}}" alt="image" style="height:100px;">
                    </td>
                    <td style="vertical-align:middle;" >{{$post->title}}</td>
                    <td style="vertical-align:middle;" class="">
                        <form action="{{route('posts.destroy',$post->id)}}" method="POST" class="float-right ml-2">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                        <a href="{{route('posts.restore',$post->id)}}" class="btn btn-success float-right  btn-sm">Restore</a>

                    </td>
                </tr>


                    @endforeach
            </tbody>
        </table>
        {{-- end table --}}
        @endif

    </div>
</div>

@endsection