routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/awal', function () {
    return view('welcome');
});
Route::get('/pegawai/cetak_pdf','PostController@generatePDF');
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'CategoryController');
    Route::resource('tags', 'TagController');
    Route::resource('posts', 'PostController');
    Route::get('/trashed_posts', 'PostController@trashed')->name('posts.trashed');
    Route::get('/restore/{id}', 'PostController@restore')->name('posts.restore');
    Route::get('/users/{user}/profile', 'UserController@edit')->name('user.edit');
    Route::post('/users/{user}/profile', 'UserController@update')->name('user.update');
    Route::get('/users/{user}/show', 'UserController@tampil')->name('user.tampil');;
});
Route::group(['middleware' => ['auth', 'VerifyAdmin']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('/users/index', 'UserController@index')->name('users.index');
    Route::post('/users/{user}/admin_role', 'UserController@make_admin')->name('users.admin_role');
    Route::post('/users/{user}/writer_role', 'UserController@make_writer')->name('users.writer_role');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];
    public function posts()
    {
        return $this->hasMany("App\Post");
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\CategoryValidation;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('categories.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryValidation $request)
    {

        Category::create($request->all());
        session()->flash('success', 'category added succesfully');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('categories.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryValidation $request, Category $category)
    {
        $category->name = $request->name;
        $category->save();
        session()->flash('success', 'Category updated succesfuly');
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        session()->flash('destroy', 'category deleted');
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
    <div class="card-header">
        {{isset($category) ? "Update Category": "Add a new Category"}}
        @if (session()->has('error'))
            <div class="alert alert-danger mt-1 mb-0 fade show flash" role="alert">
                {{session()->get('error')}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>

        @endif
    </div>
    <div class="card-body">
        <form action="{{isset($category)?route('categories.update',$category->id): route('categories.store')}}" method="POST">

            <div class="form-group">
                @csrf
                @if (isset($category))
                @method('PUT')
                @endif

                <label for="name">Category Name</label>
            <input id="name" value="{{isset($category)?$category->name:old('name')}}" class="@error('name') is-invalid @enderror form-control" type="text" name="name">

            </div>
            @error('name')
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{$message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            @enderror
            <div class="form-group">
                <button type="submit" class="btn btn-success">{{isset($category)?"Update":"Save"}}</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')
@section('content')
<div class="card">
   @if (session()->has('success'))
   <div class="alert alert-success mt-1 mb-0 fade show flash" role="alert">
      {{session()->get('success')}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
   </div>
   @endif
   @if (session()->has('destroy'))
   <div class="alert alert-danger mt-1 mb-0 fade show flash" role="alert">
      {{session()->get('destroy')}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
   </div>
   @endif
   <div class="card-header">
      <div class="clearfix">
         <span>All Categories</span>
         <a href="{{route('categories.create')}}" class="btn btn-info float-right">Add Category</a>
      </div>
   </div>
   <div class="card-body p-0">
      {{-- table --}}
      <table  class="table table-striped">
         <tbody>
            @forelse ($categories as $category)
            <tr>
               <td>{{$category->name}}</td>
               <td>
                  <form action="{{route('categories.destroy',$category->id)}}" method="POST" class="float-right ml-2">
                     @csrf
                     @method('DELETE')
                     <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                  </form>
                  <a href="{{route('categories.edit',$category->id)}}" class="btn btn-success float-right btn-sm">Edit</a>
               </td>
            </tr>
            @empty
            <p class="card-text text-center mt-3">No categories yet</p>
            @endforelse
         </tbody>
      </table>
      {{-- end table --}}
   </div>
</div>
@endsection